version: '3'
services:
  tailscale_nginx:
    container_name: tailscale_nginx
    image: "nickastete/tailscale_nginx:latest"
    cap_add:
      - NET_ADMIN
    environment:
      - USE_NGINX=true
      - TAILSCALE_TAGS=tag:dev
    env_file:
      # Once you have a Tailscale auth key, create this file as follows:
      # $ echo TAILSCALE_AUTH=YOUR_KEY_HERE > tailscale_auth.env
      - tailscale_auth.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/etc/nginx/log
    ports:
      - 8000:80